<?php
$this->headTitle('Contact');
$this->headLink()->appendStylesheet('/css/orgheiglcontact/contact.css');
?>
<section class="contact">
<h3>Contact us</h3>

<?php if ($this->error): ?>
<p class="error">
    There were one or more isues with your submission. Please correct them
    as indicated below.
</p>
<?php endif ?>

<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('contact/process'));
$form->setAttribute('method', 'post');
echo $this->form()->openTag($form);
?>
<dl class="zend_form">
	<dt><?php echo $this->formLabel($form->get('from')); ?></dt>
	<dd><?php 
	    echo $this->formInput($form->get('from'));
	    echo $this->formElementErrors($form->get('from'));
?></dd>
<dt><?php echo $this->formLabel($form->get('subject')); ?></dt>
<dd><?php 
    echo $this->formInput($form->get('subject'));
    echo $this->formElementErrors($form->get('subject'));
?></dd>

<dt><?php echo $this->formLabel($form->get('body')); ?></dt>
<dd><?php 
    echo $this->formTextarea($form->get('body'));
    echo $this->formElementErrors($form->get('body'));
?></dd>
<?php var_dump($form->get('country'));?>
<dt><?php echo $this->formLabel($form->get('country')); ?></dt>
<dd><?php 
    echo $this->formInput($form->get('country'));
    echo $this->formElementErrors($form->get('country'));
?></dd>

<dd><?php 
    echo $this->formElement($form->get('csrf'));
    echo $this->formInput($form->get('Send'));
    echo $this->formElementErrors($form->get('Send'));
?></dd>
</dl>
<?php echo $this->form()->closeTag('form')?>
</section>