# Travic-CI-Config file for \OrgHeiglContact
#
language: php
php:
  - "5.4"
  - "5.3"
       
script: phpunit --coverage-clover "clover"
before_script: composer install
after_success: curl -sL https://bit.ly/artifact-uploader | php
