# Travic-CI-Config file for \OrgHeiglContact
#
language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
       
script:
  - phpunit --coverage-text

before_script:
  - php composer.phar self-update
  - php composer.phar install

after_success:
  - curl -sL https://bit.ly/artifact-uploader | php
