<?php
$this->headTitle('Contact');
$this->headLink()->appendStylesheet('/css/orgheiglcontact/contact.css');
?>
<section class="contact">
<h2>Contact us</h2>

<?php if ($this->error): ?>
<p class="error">
    There were one or more isues with your submission. Please correct them
    as indicated below.
</p>
<?php endif ?>

<?php
$form = $this->form;
$form->setAction($this->url('contact/process'));
$form->setMethod('post');
echo $form->render($this);
