#!/usr/bin/env php
<?php

require_once('PEAR/PackageFileManager2.php');
PEAR::setErrorHandling(PEAR_ERROR_DIE);
$pfm = new PEAR_PackageFileManager2;
$e = $pfm->setOptions(
array(
    'baseinstalldir'    => '/',
    'packagedirectory'  => '.',
    'filelistgenerator' => 'file', // generate from cvs, use file for directory
    'ignore'            => array(), // ignore TODO, all files in tests/
    'installexceptions' => array(), // baseinstalldir ="/" for phpdoc
    'dir_roles'         => array(
                            'Org'       => 'php',
                           ),
    'exceptions'        => array(),
                          ));
$pfm->setPackage('Calendar');
$pfm->setSummary('PHP-based Calendar handling');
$pfm->setDescription('Handle calendars with PHP');
$pfm->setChannel('pear.heigl.org');
$pfm->setAPIVersion('1.0.0');
$pfm->setReleaseVersion('1.0.0');
$pfm->setReleaseStability('alpha');
$pfm->setAPIStability('alpha');
$pfm->setNotes('Currently this is only alpha state');
$pfm->setPackageType('php'); // this is a PEAR-style php script package
$pfm->addRelease(); // set up a release section
$pfm->setPhpDep('5.3.0');
$pfm->setPearinstallerDep('1.4.0a12');
$pfm->addMaintainer('lead', 'heiglandreas', 'Andreas Heigl', 'andreas@heigl.org');
$pfm->setLicense('MIT License', 'http://www.opensource.org/licenses/mit-license.php');
$pfm->generateContents();
 if (isset($_GET['make']) || (isset($_SERVER['argv']) && @$_SERVER['argv'][1] == 'make')) {
     $pfm->writePackageFile();
 } else {
     $pfm->debugPackageFile();
 }
